### ISSUE TITLE
一些问题...

### ISSUE THREAD

**Issue by AlanightCreeper** [qianzha/EnchantingSecretaire#1]
关于给书附魔的问题：
       用附魔笔记附魔出来的附魔书无法在铁砧上给物品附魔(生存模式)

不影响模组功能的小问题：
       1、创造模式撸破附魔记录台会掉落
       2、在记录台将附魔笔记某一页的附魔全部附到物品后，记录台依旧会显示该附魔，还可用木棍调整等级，但重新打开笔记gui点 
             击完成后会恢复正常

**Comment by qianzha** [comment]
附魔书的问题已在 v1.0.1 中修复。

其他问题：
1. 创造模式附魔台破坏掉落：下次更新再处理下（咕咕）
2. 记录台显示附魔：
	目前逻辑是附魔完仍然保留之前的选择，重新打开GUI选完成是再次选择。在木棍右击记录台时才会判断能否进行附魔。
	现在想想似乎确实很少需要连续附魔同一个魔咒的情况，下次更新（咕咕）改为附魔后清空选择好了，省去附魔后的文字渲染。

**Comment by qianzha** [comment]
v1.1.0已更新。  
创造模式的附魔台掉落问题已经修复。
附魔后的选择目前仍选择保留。新版的魔咒显示从TER（方块实体渲染）改为了HUD（OverlayGUI），只在玩家手持木棍指向记录台才会显示。

才意识到之前第二点的问题理解错了。这个是因为目前选择魔咒和等级并不会检测是否足够，“打开笔记选择会恢复”只是GUI只能在已有的附魔种类中选择。目前只在附魔操作时会判断记录的魔咒是否足够，主要是因为觉得实时检测不太值得，而其他操作时检测好像体验改进也不大，暂时还是保留现状？
